export const LEGAL_DEFINITIONS_LV = `Politiski nozīmīga persona (PNP) — persona, kura Latvijas Republikā, citā dalībvalstī vai trešajā valstī ieņem vai ir ieņēmusi nozīmīgu publisku amatu, tai skaitā valsts varas augstākā amatpersona, valsts administratīvās vienības (pašvaldības) vadītājs, valdības vadītājs, ministrs (ministra vietnieks vai ministra vietnieka vietnieks, ja attiecīgajā valstī ir šāds amats), valsts sekretārs vai cita augsta līmeņa amatpersona valdībā vai valsts administratīvajā vienībā (pašvaldībā), parlamenta deputāts vai līdzīgas likumdošanas struktūras loceklis, politiskās partijas vadības struktūras (valdes) loceklis, konstitucionālās tiesas, augstākās tiesas vai cita līmeņa tiesas tiesnesis (tiesu institūcijas loceklis), augstākās revīzijas (audita) iestādes padomes vai valdes loceklis, centrālās bankas padomes vai valdes loceklis, vēstnieks, pilnvarotais lietvedis, bruņoto spēku augstākais virsnieks, valsts kapitālsabiedrības padomes vai valdes loceklis, starptautiskas organizācijas vadītājs (direktors, direktora vietnieks) un valdes loceklis vai persona, kas šajā organizācijā ieņem līdzvērtīgu amatu.

Politiski nozīmīgas personas ģimenes loceklis — persona, kura ir PNP a) laulātais vai laulātajam pielīdzināma persona. Persona par laulātajam pielīdzināmu personu uzskatāma tikai tad, ja attiecīgās valsts likumi tai nosaka šādu statusu, b) bērns vai politiski nozīmīgas personas laulātā vai laulātajam pielīdzināmas personas bērns, viņa laulātais vai laulātajam pielīdzināma persona, c) vecāks, vecvecāks vai mazbērns, d) brālis vai māsa.

Ar politiski nozīmīgu personu cieši saistīta persona — fiziskā persona, par kuru ir zināms, ka tai ir darījuma vai citas ciešas attiecības ar PNP vai tā ir akcionārs vai dalībnieks vienā un tajā pašā komercsabiedrībā ar PNP, kā arī fiziskā persona, kura ir vienīgā tāda juridiska veidojuma īpašnieks, par ko ir zināms, ka tas faktiski izveidots PNP labā.

Patiesais labuma guvējs (PLG) — fiziskā persona, kura ir klienta — juridiskās personas — īpašnieks vai kura kontrolē klientu, vai kuras vārdā, labā, interesēs tiek nodibinātas darījuma attiecības vai tiek veikts gadījuma rakstura darījums, un tā ir vismaz: a) attiecībā uz juridiskajām personām — fiziskā persona, kurai tiešas vai netiešas līdzdalības veidā pieder vairāk nekā 25 procenti no juridiskās personas kapitāla daļām vai balsstiesīgajām akcijām vai kura to tiešā vai netiešā veidā kontrolē, b) attiecībā uz juridiskiem veidojumiem — fiziskā persona, kurai pieder vai kuras interesēs ir izveidots vai darbojas juridisks veidojums vai kura tiešā vai netiešā veidā īsteno kontroli pār to, tostarp kura ir šāda veidojuma dibinātājs, pilnvarnieks vai pārraudzītājs (pārvaldnieks).

Sankcijas – atbilstoši starptautiskajām tiesībām attiecībā uz sankciju subjektu noteikti ierobežojumi, kurus pieņēmusi Apvienoto Nāciju Organizācija vai Eiropas Savienība, vai cita starptautiskā organizācija, kuras dalībvalsts ir Latvija un kuri tieši piemērojami vai ievesti Latvijā, kā arī atbilstoši Latvijas normatīvajiem aktiem un starptautiskajām tiesībām attiecībā uz sankciju subjektu noteikti ierobežojumi, kurus noteicis Ministru kabinets.`;
